/* The following code was generated by JFlex 1.7.0 */

package Analizadores;
import java_cup.runtime.*;
import java.util.ArrayList;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/AnalizadoresTexto/LexicoCSS.jflex</tt>
 */
public class LexicoCSS implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMENTMULTI = 2;
  public static final int COMENTSIMPLE = 4;
  public static final int STRING = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  7, 11,  6,  6,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     6,  0,  8,  0,  0,  0,  0,  5, 37, 38,  9,  0, 39, 41,  2, 10, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 36, 42,  0, 40,  0,  0, 
     0, 25, 21, 26, 17, 24, 35, 20, 19, 16,  3, 28, 31,  3, 30, 22, 
     3,  3, 23, 33, 18, 29,  3, 14,  3,  3, 34,  0,  0,  0,  0,  4, 
     0, 25, 21, 26, 17, 24, 35, 20, 19, 16,  3, 28, 31,  3, 30, 22, 
     3,  3, 23, 33, 18, 29,  3, 14,  3,  3, 34, 12,  0, 13,  0,  0, 
     0,  0,  0,  0,  0, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\1\1\7\1\10\6\4\1\1\2\4\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\2\20\1\21\1\22"+
    "\1\23\1\0\1\24\1\25\1\0\1\4\1\0\6\4"+
    "\1\0\2\4\1\26\1\0\1\4\1\0\3\4\1\27"+
    "\1\0\2\4\1\0\2\4\1\0\1\4\1\0\2\4"+
    "\1\0\1\4\1\0\2\4\2\30\1\31\2\32\2\33"+
    "\1\4\1\0\1\4\2\34\1\35\1\36\1\0\1\4"+
    "\1\0\1\4\1\0\1\4\1\0\1\4\2\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\254\0\u0102"+
    "\0\u012d\0\254\0\254\0\u0158\0\254\0\254\0\u0183\0\u01ae"+
    "\0\u01d9\0\u0204\0\u022f\0\u025a\0\u0285\0\u02b0\0\u02db\0\254"+
    "\0\254\0\254\0\254\0\254\0\254\0\254\0\254\0\u0306"+
    "\0\254\0\254\0\254\0\u0331\0\254\0\254\0\u035c\0\u0387"+
    "\0\u03b2\0\u03dd\0\u0408\0\u0433\0\u045e\0\u0489\0\u04b4\0\u04df"+
    "\0\u050a\0\u0535\0\254\0\u0560\0\u058b\0\u05b6\0\u05e1\0\u060c"+
    "\0\u0637\0\u0102\0\u0662\0\u068d\0\u06b8\0\u06e3\0\u070e\0\u0739"+
    "\0\u0764\0\u078f\0\u07ba\0\u07e5\0\u0810\0\u083b\0\u0866\0\u0891"+
    "\0\u08bc\0\u08e7\0\254\0\u0102\0\u0102\0\254\0\u0102\0\254"+
    "\0\u0102\0\u0912\0\u093d\0\u0968\0\254\0\u0102\0\u0102\0\u0102"+
    "\0\u0993\0\u09be\0\u09e9\0\u0a14\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0"+
    "\0\254\0\u0102";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\1\5\1\11\2\12\1\13"+
    "\1\5\1\14\1\0\1\15\1\16\1\17\1\5\3\10"+
    "\1\20\1\10\1\21\1\10\1\22\1\10\1\23\1\24"+
    "\1\5\4\10\1\25\1\26\1\10\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\11\37\1\40\1\37"+
    "\1\0\46\37\1\41\43\37\10\42\1\43\42\42\54\0"+
    "\1\6\52\0\1\10\1\0\2\10\11\0\1\10\1\0"+
    "\13\10\1\0\4\10\1\0\3\10\7\0\5\44\1\0"+
    "\45\44\11\0\1\45\1\46\41\0\1\10\1\0\2\10"+
    "\11\0\1\10\1\47\1\50\12\10\1\0\4\10\1\0"+
    "\3\10\10\0\1\10\1\0\2\10\11\0\1\10\1\51"+
    "\1\52\12\10\1\0\4\10\1\0\3\10\10\0\1\10"+
    "\1\0\2\10\11\0\1\10\1\0\6\10\1\53\2\10"+
    "\1\54\1\10\1\0\4\10\1\0\3\10\10\0\1\10"+
    "\1\0\2\10\11\0\1\10\1\0\4\10\1\55\6\10"+
    "\1\0\4\10\1\0\3\10\10\0\1\10\1\0\2\10"+
    "\11\0\1\10\1\0\13\10\1\0\3\10\1\56\1\0"+
    "\3\10\10\0\1\10\1\0\2\10\11\0\1\10\1\0"+
    "\6\10\1\57\4\10\1\0\4\10\1\0\3\10\26\0"+
    "\2\60\33\0\1\10\1\0\2\10\11\0\1\10\1\60"+
    "\1\61\12\10\1\0\4\10\1\0\3\10\10\0\1\10"+
    "\1\0\2\10\11\0\1\10\1\0\6\10\1\62\4\10"+
    "\1\0\4\10\1\0\3\10\21\0\1\41\45\0\1\63"+
    "\66\0\1\64\32\0\1\10\1\0\2\10\11\0\1\10"+
    "\1\0\1\10\1\65\11\10\1\0\4\10\1\0\3\10"+
    "\33\0\1\66\27\0\1\10\1\0\2\10\11\0\1\10"+
    "\1\0\4\10\1\67\6\10\1\0\4\10\1\0\3\10"+
    "\10\0\1\10\1\0\2\10\11\0\1\10\1\0\7\10"+
    "\1\70\3\10\1\0\4\10\1\0\3\10\10\0\1\10"+
    "\1\0\2\10\11\0\1\10\1\0\12\10\1\71\1\0"+
    "\4\10\1\0\3\10\10\0\1\10\1\0\2\10\11\0"+
    "\1\10\1\0\5\10\1\72\5\10\1\0\4\10\1\0"+
    "\3\10\10\0\1\10\1\0\2\10\11\0\1\10\1\73"+
    "\1\74\12\10\1\0\4\10\1\0\3\10\10\0\1\10"+
    "\1\0\2\10\11\0\1\10\1\0\13\10\1\0\3\10"+
    "\1\75\1\0\3\10\51\0\1\76\11\0\1\10\1\0"+
    "\2\10\11\0\1\10\1\0\13\10\1\0\4\10\1\0"+
    "\1\10\1\77\1\10\10\0\1\10\1\0\2\10\11\0"+
    "\1\10\1\0\13\10\1\0\2\10\1\100\1\10\1\0"+
    "\3\10\31\0\1\101\31\0\1\10\1\0\2\10\11\0"+
    "\1\10\1\0\2\10\1\102\10\10\1\0\4\10\1\0"+
    "\3\10\32\0\1\103\30\0\1\10\1\0\2\10\11\0"+
    "\1\10\1\0\3\10\1\104\7\10\1\0\4\10\1\0"+
    "\3\10\10\0\1\10\1\0\2\10\11\0\1\10\1\0"+
    "\1\10\1\105\11\10\1\0\4\10\1\0\3\10\10\0"+
    "\1\10\1\0\2\10\11\0\1\10\1\0\13\10\1\106"+
    "\1\107\3\10\1\0\3\10\33\0\1\110\27\0\1\10"+
    "\1\0\2\10\11\0\1\10\1\0\4\10\1\111\6\10"+
    "\1\0\4\10\1\0\3\10\10\0\1\10\1\0\2\10"+
    "\11\0\1\10\1\0\6\10\1\112\4\10\1\0\4\10"+
    "\1\0\3\10\37\0\1\113\23\0\1\10\1\0\2\10"+
    "\11\0\1\10\1\0\10\10\1\114\2\10\1\0\4\10"+
    "\1\0\3\10\10\0\1\10\1\0\2\10\11\0\1\10"+
    "\1\0\2\10\1\115\10\10\1\0\4\10\1\0\3\10"+
    "\32\0\1\116\30\0\1\10\1\0\2\10\11\0\1\10"+
    "\1\0\3\10\1\117\7\10\1\0\4\10\1\0\3\10"+
    "\31\0\1\120\31\0\1\10\1\0\2\10\11\0\1\10"+
    "\1\0\2\10\1\121\10\10\1\0\4\10\1\0\3\10"+
    "\10\0\1\10\1\0\2\10\11\0\1\10\1\0\10\10"+
    "\1\122\2\10\1\0\4\10\1\0\3\10\33\0\1\123"+
    "\27\0\1\10\1\0\2\10\11\0\1\10\1\0\4\10"+
    "\1\124\6\10\1\0\4\10\1\0\3\10\45\0\1\125"+
    "\15\0\1\10\1\0\2\10\11\0\1\10\1\0\13\10"+
    "\1\0\2\10\1\126\1\10\1\0\3\10\10\0\1\10"+
    "\1\0\2\10\11\0\1\10\1\0\7\10\1\127\3\10"+
    "\1\0\4\10\1\0\3\10\10\0\1\10\1\0\2\10"+
    "\11\0\1\10\1\0\7\10\1\130\3\10\1\0\4\10"+
    "\1\0\3\10\36\0\1\131\24\0\1\10\1\0\2\10"+
    "\11\0\1\10\1\0\7\10\1\132\3\10\1\0\4\10"+
    "\1\0\3\10\35\0\1\133\25\0\1\10\1\0\2\10"+
    "\11\0\1\10\1\0\6\10\1\134\4\10\1\0\4\10"+
    "\1\0\3\10\44\0\1\135\16\0\1\10\1\0\2\10"+
    "\11\0\1\10\1\0\13\10\1\0\1\10\1\136\2\10"+
    "\1\0\3\10\45\0\1\137\15\0\1\10\1\0\2\10"+
    "\11\0\1\10\1\0\13\10\1\0\2\10\1\140\1\10"+
    "\1\0\3\10\30\0\1\141\32\0\1\10\1\0\2\10"+
    "\11\0\1\10\1\0\1\10\1\142\11\10\1\0\4\10"+
    "\1\0\3\10\7\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2795];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\1\1\1\11\2\1\2\11\1\1\2\11"+
    "\11\1\10\11\1\1\3\11\1\0\2\11\1\0\1\1"+
    "\1\0\6\1\1\0\2\1\1\11\1\0\1\1\1\0"+
    "\4\1\1\0\2\1\1\0\2\1\1\0\1\1\1\0"+
    "\2\1\1\0\1\1\1\0\2\1\1\11\2\1\1\11"+
    "\1\1\1\11\2\1\1\0\1\1\1\11\3\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\11"+
    "\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    String cadena="";
    int llamadaString = 0;
    int ESTADOACTUAL = 0;

    public Symbol addSymbol(Symbol s){
        System.out.println(s.value.toString());
        return s;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicoCSS(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(Symc.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error Lexico: <<"+yytext()+">> ["+yyline+" , "+yycolumn+"]");
            } 
            // fall through
          case 32: break;
          case 2: 
            { return addSymbol(new Symbol(Symc.tEntero,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 33: break;
          case 3: 
            { return addSymbol(new Symbol(Symc.tPunto,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 34: break;
          case 4: 
            { return addSymbol(new Symbol(Symc.tId,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 35: break;
          case 5: 
            { /* ignorar */
            } 
            // fall through
          case 36: break;
          case 6: 
            { ESTADOACTUAL = YYINITIAL; yybegin(STRING);
            } 
            // fall through
          case 37: break;
          case 7: 
            { return addSymbol(new Symbol(Symc.tLlaveA,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 38: break;
          case 8: 
            { return addSymbol(new Symbol(Symc.tLlaveC,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 39: break;
          case 9: 
            { return addSymbol(new Symbol(Symc.tDosPuntos,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 40: break;
          case 10: 
            { return addSymbol(new Symbol(Symc.tParA,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 41: break;
          case 11: 
            { return addSymbol(new Symbol(Symc.tParC,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 42: break;
          case 12: 
            { return addSymbol(new Symbol(Symc.tComa,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 43: break;
          case 13: 
            { return addSymbol(new Symbol(Symc.tIgual,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 44: break;
          case 14: 
            { return addSymbol(new Symbol(Symc.tGuion,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 45: break;
          case 15: 
            { return addSymbol(new Symbol(Symc.tPuntoComa,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 46: break;
          case 16: 
            { 
            } 
            // fall through
          case 47: break;
          case 17: 
            { yybegin(ESTADOACTUAL);
            } 
            // fall through
          case 48: break;
          case 18: 
            { cadena += yytext();
            } 
            // fall through
          case 49: break;
          case 19: 
            { yybegin(ESTADOACTUAL);
            String temporal = cadena; 
            cadena = "";
            return addSymbol( new Symbol(Symc.tCadena, yychar,yyline,temporal) );
            } 
            // fall through
          case 50: break;
          case 20: 
            { ESTADOACTUAL = YYINITIAL; yybegin(COMENTMULTI);
            } 
            // fall through
          case 51: break;
          case 21: 
            { ESTADOACTUAL = YYINITIAL; yybegin(COMENTSIMPLE);
            } 
            // fall through
          case 52: break;
          case 22: 
            { return addSymbol(new Symbol(Symc.tCaracter,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 53: break;
          case 23: 
            { return addSymbol(new Symbol(Symc.tRgb,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 54: break;
          case 24: 
            { return addSymbol(new Symbol(Symc.tSize,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 55: break;
          case 25: 
            { return addSymbol(new Symbol(Symc.tFont,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 56: break;
          case 26: 
            { return addSymbol(new Symbol(Symc.tWidth,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 57: break;
          case 27: 
            { return addSymbol(new Symbol(Symc.tHight,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 58: break;
          case 28: 
            { return addSymbol(new Symbol(Symc.tAlign,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 59: break;
          case 29: 
            { return addSymbol(new Symbol(Symc.tColor,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 60: break;
          case 30: 
            { return addSymbol(new Symbol(Symc.tBorder,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 61: break;
          case 31: 
            { return addSymbol(new Symbol(Symc.tBackground,yycolumn,yyline,yytext()));
            } 
            // fall through
          case 62: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
