
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Symc {
  /* terminals */
  public static final int tLlaveA = 20;
  public static final int tLeft = 13;
  public static final int tGuion = 2;
  public static final int tCadena = 9;
  public static final int tCadenaInterna = 10;
  public static final int tWidth = 18;
  public static final int tHight = 19;
  public static final int tColor = 3;
  public static final int tNumeral = 5;
  public static final int tFont = 16;
  public static final int tRight = 17;
  public static final int tRGB = 8;
  public static final int tPuntoComa = 6;
  public static final int tBack = 22;
  public static final int EOF = 0;
  public static final int tBorder = 11;
  public static final int tCaracter = 15;
  public static final int error = 1;
  public static final int tEntero = 14;
  public static final int tCenter = 21;
  public static final int tId = 12;
  public static final int tDosPuntos = 4;
  public static final int tLlaveC = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tGuion",
  "tColor",
  "tDosPuntos",
  "tNumeral",
  "tPuntoComa",
  "tLlaveC",
  "tRGB",
  "tCadena",
  "tCadenaInterna",
  "tBorder",
  "tId",
  "tLeft",
  "tEntero",
  "tCaracter",
  "tFont",
  "tRight",
  "tWidth",
  "tHight",
  "tLlaveA",
  "tCenter",
  "tBack"
  };
}

