
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Symh {
  /* terminals */
  public static final int tMenorQue = 10;
  public static final int tTitle = 4;
  public static final int tMayorQue = 11;
  public static final int tCadena = 13;
  public static final int tDiagonal = 12;
  public static final int tIgual = 9;
  public static final int tNoufe = 5;
  public static final int tId = 8;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int tHtml = 2;
  public static final int tBody = 7;
  public static final int tDiv = 6;
  public static final int tCadenaInterna = 14;
  public static final int tHead = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tHtml",
  "tHead",
  "tTitle",
  "tNoufe",
  "tDiv",
  "tBody",
  "tId",
  "tIgual",
  "tMenorQue",
  "tMayorQue",
  "tDiagonal",
  "tCadena",
  "tCadenaInterna"
  };
}

